CREATE TABLE entries (id TEXT PRIMARY KEY, data TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE settings (id INTEGER PRIMARY KEY CHECK(id=1), opening_balance INTEGER NOT NULL DEFAULT 0);
INSERT INTO settings(id,opening_balance) VALUES (1,0);
CREATE TABLE sessions (token TEXT PRIMARY KEY, expires INTEGER NOT NULL);
CREATE TABLE login_attempts (ip TEXT PRIMARY KEY, attempts INTEGER NOT NULL, reset_at INTEGER NOT NULL);
